### ISSUE TITLE
Path to parent folder must be absolute

### ISSUE THREAD

**Issue by Niaw** [IbrahimTanyalcin/camToMP4#1]
Hi Ibrahim,

Thank you so much for your script! It was a big help for me, I used it for a good friend who has been robbed.

At first, I did not understood why it wasn't working.

I was using the same command line you proposed:
`/bin/bash /path/to/camToMP4.sh /path/to/parentFolder/ -m allmp4s -c merged --prog -q`

But with a relative path or a dot (current folder) for the parent folder.

I had a view of the folders processed, but with the error "No file or directory of this type" (translation from french) in the end of each folder processed.

Removing the "quiet" argument show me the FFMPEG error (when using a dot for the current folder):
`[concat @ 0x55a11c512380] Impossible to open '/dev/fd/./1685387507_0000//0000.media'`

Using an absolute path for the parent folder solved the problem.

Thanks a lot again!

P.S.: It isn't an issue, more like adding this information in the README.

**Comment by IbrahimTanyalcin** [comment]
Hi @Niaw , 

Can you check this [PR](https://github.com/IbrahimTanyalcin/cam-to-mp4/pull/2) please.
If you clone the branch it is pointing to (`convert-relative-paths-to-abs`) or latest `master` and give it a try, it should work for BOTH relative & absolute paths.

I have tried in my local system and it works. If you can give it a try and confirm that would be nice. Ty

**Comment by Niaw** [comment]
Thank you @IbrahimTanyalcin , as soon as I have the time, I will test it and report to you.
